[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
moonmap_pulse = "3R7mbvtHmbBwX9KwXmf72ZFqzkyGfFRM8VWELfKHEf4g"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "localnet"
# wallet = "~/.config/solana/id.json"
wallet = "~/.config/solana/moonmap_authority.json"

[scripts]
test = "ANCHOR_LOG_LEVEL=debug RUST_LOG=debug yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
postdeploy = "anchor run ix_initialize_global"